{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "65c22b3f-f765-48f2-a764-af7bbd95b2a8",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''Programming Set 2\n",
    "\n",
    "This assignment will develop your proficiency with Python's control flows.\n",
    "'''\n",
    "\n",
    "def shift_letter(letter, shift):\n",
    "    '''Shift Letter.\n",
    "\n",
    "    Shift a letter right by the given number.\n",
    "    Wrap the letter around if it reaches the end of the alphabet.\n",
    "\n",
    "    Examples:\n",
    "    shift_letter(\"A\", 0) -> \"A\"\n",
    "    shift_letter(\"A\", 2) -> \"C\"\n",
    "    shift_letter(\"Z\", 1) -> \"A\"\n",
    "    shift_letter(\"X\", 5) -> \"C\"\n",
    "    shift_letter(\" \", _) -> \" \"\n",
    "\n",
    "    *Note: the single underscore `_` is used to acknowledge the presence\n",
    "        of a value without caring about its contents.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    letter: str\n",
    "        a single uppercase English letter, or a space.\n",
    "    shift: int\n",
    "        the number by which to shift the letter.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        the letter, shifted appropriately, if a letter.\n",
    "        a single space if the original letter was a space.\n",
    "    '''\n",
    "    # Replace `pass` with your code.\n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "def shift_letter(letter, shift):\n",
    "    if letter == \" \":\n",
    "        return \" \"\n",
    "    \n",
    "    # unicode of A as the base to be shifted around\n",
    "    base = ord('A')\n",
    "    # unicode of given letter - base letter of A + value to be shifted by and also 26 is to do the wrapping around bit\n",
    "    shifted_position = (ord(letter) - base + shift) % 26\n",
    "    # chr turns it back into a letter after being shifted\n",
    "    return chr(base + shifted_position)\n",
    "\n",
    "def caesar_cipher(message, shift):\n",
    "    '''Caesar Cipher.\n",
    "\n",
    "    Apply a shift number to a string of uppercase English letters and spaces.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    message: str\n",
    "        a string of uppercase English letters and spaces.\n",
    "    shift: int\n",
    "        the number by which to shift the letters.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        the message, shifted appropriately.\n",
    "    '''\n",
    "    # Replace `pass` with your code.\n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    def caesar_cipher(message, shift):\n",
    "    def shift_letter(letter, shift):\n",
    "        if letter == \" \":\n",
    "            return \" \"\n",
    "    # return letter version of (unicode given - unicode base + given shift) + the base again\n",
    "        base = ord('A')\n",
    "        return chr((ord(letter) - base + shift) % 26 + base)\n",
    "\n",
    "    # does the thing and joins the letters\n",
    "    return ''.join(shift_letter(char, shift) for char in message)\n",
    "\n",
    "def shift_by_letter(letter, letter_shift):\n",
    "    '''Shift By Letter.\n",
    "\n",
    "    Shift a letter to the right using the number equivalent of another letter.\n",
    "    The shift letter is any letter from A to Z, where A represents 0, B represents 1,\n",
    "        ..., Z represents 25.\n",
    "\n",
    "    Examples:\n",
    "    shift_by_letter(\"A\", \"A\") -> \"A\"\n",
    "    shift_by_letter(\"A\", \"C\") -> \"C\"\n",
    "    shift_by_letter(\"B\", \"K\") -> \"L\"\n",
    "    shift_by_letter(\" \", _) -> \" \"\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    letter: str\n",
    "        a single uppercase English letter, or a space.\n",
    "    letter_shift: str\n",
    "        a single uppercase English letter.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        the letter, shifted appropriately.\n",
    "    '''\n",
    "    # Replace `pass` with your code.\n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    def shift_by_letter(letter, letter_shift):\n",
    "        if letter == \" \":\n",
    "            return \" \"\n",
    "    # get base, get amount to shift by, get final letter duh\n",
    "        base = ord('A')\n",
    "        shifted_amount = ord(letter_shift) - base\n",
    "        final = chr((ord(letter) - base + shifted_amount) % 26 + base)\n",
    "\n",
    "    # duh\n",
    "        return final\n",
    "\n",
    "def vigenere_cipher(message, key):\n",
    "    '''Vigenere Cipher.\n",
    "\n",
    "    Encrypts a message using a keyphrase instead of a static number.\n",
    "    Every letter in the message is shifted by the number represented by the\n",
    "        respective letter in the key.\n",
    "    Spaces should be ignored.\n",
    "\n",
    "    Example:\n",
    "    vigenere_cipher(\"A C\", \"KEY\") -> \"K A\"\n",
    "\n",
    "    If needed, the key is extended to match the length of the message.\n",
    "        If the key is \"KEY\" and the message is \"LONGTEXT\",\n",
    "        the key will be extended to be \"KEYKEYKE\".\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    message: str\n",
    "        a string of uppercase English letters and spaces.\n",
    "    key: str\n",
    "        a string of uppercase English letters. Will never be longer than the message.\n",
    "        Will never contain spaces.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        the message, shifted appropriately.\n",
    "    '''\n",
    "    # Replace `pass` with your code.\n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    def vigenere_cipher(message, key):\n",
    "    result = []\n",
    "    # length counter for the key\n",
    "    key_length = len(key)\n",
    "    # for every index entry it does the following function\n",
    "    for i, char in enumerate(message):\n",
    "        if char == ' ':\n",
    "            # Spaces stay the same, but key index still advances\n",
    "            result.append(' ')\n",
    "        else:\n",
    "            base = ord('A')\n",
    "            # wraps the number and i stole the 2nd line from the other code\n",
    "            shift = ord(key[i % key_length]) - base\n",
    "            final = chr((ord(char) - base + shift) % 26 + base)\n",
    "            # the applier\n",
    "            result.append(final)\n",
    "    return ''.join(result)\n",
    "\n",
    "def scytale_cipher(message, shift):\n",
    "    '''Scytale Cipher.\n",
    "\n",
    "    Encrypts a message by simulating a scytale cipher.\n",
    "\n",
    "    A scytale is a cylinder around which you can wrap a long strip of\n",
    "        parchment that contained a string of apparent gibberish. The parchment,\n",
    "        when read using the scytale, would reveal a message due to every nth\n",
    "        letter now appearing next to each other, revealing a proper message.\n",
    "    This encryption method is obsolete and should never be used to encrypt\n",
    "        data in production settings.\n",
    "\n",
    "    You may read more about the method here:\n",
    "        https://en.wikipedia.org/wiki/Scytale\n",
    "\n",
    "    You may follow this algorithm to implement a scytale-style cipher:\n",
    "    1. Take a message to be encoded and a \"shift\" number.\n",
    "        For this example, we will use \"INFORMATION_AGE\" as\n",
    "        the message and 3 as the shift.\n",
    "    2. Check if the length of the message is a multiple of\n",
    "        the shift. If it is not, add additional underscores\n",
    "        to the end of the message until it is.\n",
    "        In this example, \"INFORMATION_AGE\" is already a multiple of 3,\n",
    "        so we will leave it alone.\n",
    "    3. This is the tricky part. Construct the encoded message.\n",
    "        For each index i in the encoded message, use the character at the index\n",
    "        (i // shift) + (len(message) // shift) * (i % shift) of the raw message.\n",
    "        If this number doesn't make sense, you can play around with the cipher at\n",
    "         https://dencode.com/en/cipher/scytale to try to understand it.\n",
    "    4. Return the encoded message. In this case,\n",
    "        the output should be \"IMNNA_FTAOIGROE\".\n",
    "\n",
    "    Example:\n",
    "    scytale_cipher(\"INFORMATION_AGE\", 3) -> \"IMNNA_FTAOIGROE\"\n",
    "    scytale_cipher(\"INFORMATION_AGE\", 4) -> \"IRIANMOGFANEOT__\"\n",
    "    scytale_cipher(\"ALGORITHMS_ARE_IMPORTANT\", 8) -> \"AOTSRIOALRH_EMRNGIMA_PTT\"\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    message: str\n",
    "        a string of uppercase English letters and underscores (underscores represent spaces)\n",
    "    shift: int\n",
    "        a positive int that does not exceed the length of message\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        the encoded message\n",
    "    '''\n",
    "    # Replace `pass` with your code.\n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    def scytale_cipher(message, shift):\n",
    "    length = len(message)\n",
    "    if length % shift != 0:\n",
    "        # add shift padding so its the right length because this encryption sucks\n",
    "        padding = shift - (length % shift)\n",
    "        message += '_' * padding\n",
    "        length = len(message)\n",
    "    \n",
    "    encoded = []\n",
    "    # does the actual \"encoding\"\n",
    "    rows = length // shift\n",
    "    for i in range(length):\n",
    "        # shifts by row\n",
    "        index = (i // shift) + rows * (i % shift)\n",
    "        encoded.append(message[index])\n",
    "        \n",
    "    return ''.join(encoded)\n",
    "\n",
    "def scytale_decipher(message, shift):\n",
    "    '''Scytale De-cipher.\n",
    "\n",
    "    Decrypts a message that was originally encrypted with the `scytale_cipher` function above.\n",
    "\n",
    "    Example:\n",
    "    scytale_decipher(\"IMNNA_FTAOIGROE\", 3) -> \"INFORMATION_AGE\"\n",
    "    scytale_decipher(\"AOTSRIOALRH_EMRNGIMA_PTT\", 8) -> \"ALGORITHMS_ARE_IMPORTANT\"\n",
    "    scytale_decipher(\"IRIANMOGFANEOT__\", 4) -> \"INFORMATION_AGE_\"\n",
    "\n",
    "    There is no further brief for this number.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    message: str\n",
    "        a string of uppercase English letters and underscores (underscores represent spaces)\n",
    "    shift: int\n",
    "        a positive int that does not exceed the length of message\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        the decoded message\n",
    "    '''\n",
    "    # Replace `pass` with your code.\n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    def scytale_decipher(message, shift):\n",
    "    length = len(message)\n",
    "    rows = length // shift\n",
    "    final = []\n",
    "    for i in range(length):\n",
    "        # im so serious you just swap shift and rows around and flip the signs\n",
    "        index = (i % rows) * shift + (i // rows)\n",
    "        final.append(message[index])\n",
    "        \n",
    "    return ''.join(final)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
